version: '3'
services:
  db:
    image: mysql:8.0.22
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/myapp'
    environment: 
      - 'MYSQL_PASSWORD=password'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db